pipeline:
  build:
    image: alpine:latest
    commands:
        - apk --no-cache add python py-pip ca-certificates py-psycopg2 postgresql-client xz
        - pip install -r requirements.txt
        - pip install -r tests/requirements.txt
        - pip install -e .
        - echo "localhost:5432:*:postgres:secret" > ~/.pgpass
        - chmod 600 ~/.pgpass
        - psql -h localhost -U postgres -c 'CREATE DATABASE antismash'
        - xzcat tests/test.sql.xz | psql -h localhost -U postgres antismash > /dev/null
        - py.test -v

  slack:
    image: plugins/slack
    channel: bots
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
      event: push

  email:
    image: drillster/drone-email
    from: ci@secondarymetabolites.org
    host: mail.secondarymetabolites.org
    username: antismash
    secrets: [ email_password ]
    when:
      status: [ success, failure ]
      event: push

services:
  database:
    image: postgres:9.5
    environmet:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
